# TYPE: Describes the type of issue or pull request

- name: "type-breaking"
  description: "Introduces a breaking change."
  color: d50000

- name: "type-chore"
  description: "General maintenance and other necessary (but less impactful) tasks."
  color: 90caf9

- name: "type-feature"
  description: "Brand new functionality, features, pages, workflows, endpoints, etc."
  color: 01579b

- name: "type-fix"
  description: "Iterations on existing features or infrastructure."
  color: 1e88e5

- name: "type-discussion"
  description: "Questions, proposals and info that requires discussion."
  color: 64b5f6

- name: "type-documentation"
  description: "Related to documentation and information."
  color: 42a5f5

- name: "type-quality"
  description: "Related to testing and improving quality assurance."
  color: 1976d2

- name: "type-security"
  description: "Something is vulnerable or not secure."
  color: 0277bd

- name: "type-design"
  description: "Related to presentation layer, user interface, styling, and UX."
  color: 2196f3

# PRIORITY

- name: "priority-low"
  description: "Low priority"
  color: ff8a80

- name: "priority-medium"
  description: "Medium priority"
  color: ff5252

- name: "priority-high"
  description: "High priority"
  color: ff1744

- name: "priority-critical"
  description: "Critical (top priority)"
  color: d50000

# STATUS - Decision state of the issue or pull request

- name: "status-wont-fix"
  description: "Decision made to not fix this issue"
  color: cccccc

- name: "status-duplicate"
  description: "Decision made this is a duplicate of an existing issue"
  color: cccccc

- name: "status-blocked"
  description: "Decision made this issue is currently blocked"
  color: d50000

- name: "status-slfb"
  description: "Decision made to setup short-lived feature branch"
  color: 558b2f

# WORK - Describes the kind of work involved in resolving the issue
# Uses the Cynefin Framework
# https://en.wikipedia.org/wiki/Cynefin_framework

- name: "work-chaotic"
  description: "The situation is chaotic, novel practices used."
  color: ffab00

- name: "work-complex"
  description: "The situation is complex, emergent practices used."
  color: ffc400

- name: "work-complicated"
  description: "The situation is complicated, good practices used."
  color: ffd740

- name: "work-obvious"
  description: "The situation is obvious, best practices used."
  color: ffe57f
