name: AGILE-DEVELOPMENT

on:

  workflow_call:

jobs: 

  slfb:
    name: Setup Dev for SLFB
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:

      - name: Checkout Main Branch
        uses: actions/checkout@v3

      - name: Set SLFB Name
        id: slfb-name
        run: |
          name=$(echo ${{ github.event.issue.title }} | tr " " "-")
          slfb=$(echo "${{github.event.issue.number}}-${name}" )
          echo "${slfb}"
          echo "SLFB=$slfb" >> $GITHUB_OUTPUT

      - name: Setup SLFB
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh issue develop ${{github.event.issue.number}} --base main --name "${{ steps.slfb-name.outputs.SLFB }}" || gh issue comment ${{github.event.issue.number}} --body "GitHub Action - Short-Lived Feature Branch ( ${{ steps.slfb-name.outputs.SLFB }} ) already exists"

      - name: Comment for Branch Checkout
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          comment="
          ### Check out SLFB in your Dev environment

          \`\`\`
          git fetch origin
          git checkout -b ${{ steps.slfb-name.outputs.SLFB }}
          \`\`\`

          "
          echo $comment
          gh issue comment ${{github.event.issue.number}} --body "$comment"

      - name: Message SLFB
        run: echo "### SLFB Created :thumbsup:" >> $GITHUB_STEP_SUMMARY

#      - name: Setup Codespace
#        run: gh codespace create --display-name "${{ steps.slfb-name.outputs.SLFB }}" --repo "${{ github.repository }}" --branch "${{ steps.slfb-name.outputs.SLFB }}" --machine "basicLinux32gb" --retention-period "48h" --default-permissions
#        env:
#          GH_TOKEN: ${{ secrets.PR_MERGE }}

#      - name: Message Codespace
#        run: echo "### Codespace Created :thumbsup:" >> $GITHUB_STEP_SUMMARY

      - name: Checkout SLFB
        run: | 
          git fetch origin
          git checkout -b ${{ steps.slfb-name.outputs.SLFB }}
        
      - name: Create/Reopen Pull Request
        run: gh pr create -t ${{ steps.slfb-name.outputs.SLFB }} -b "Created by Github Action (AGILE-DEVELOPMENT)" --base main --head $(git branch --show-current) || gh pr edit ${{ steps.slfb-name.outputs.SLFB }} -b "Reopened by Github action" -t ${{ steps.slfb-name.outputs.SLFB }} && gh pr reopen ${{ steps.slfb-name.outputs.SLFB }}
        env:
          GH_TOKEN: ${{ github.token }}
