# Agile Development Workflow
name: AGILE-DEVELOPMENT
run-name: Agile Development

on:

  workflow_call:

jobs: 

  create-slfb:
    name: Create Branch
    runs-on: ubuntu-latest 
    steps:

      - name: Checkout Feature Branch
        uses: actions/checkout@v3

      - name: Set SLFB Name
        id: slfb-name
        run: |
          name=$(echo ${{ github.event.issue.title }} | tr " " "-")
          slfb=$(echo ${{github.event.issue.number}}+=$slfb)
          echo "SLFB=$slfb" >> $GITHUB_OUTPUT

      - name: Test
        run: echo ${{ steps.slfb-name.outputs.SLFB }}

#      - name: Issue Develop
#        run: gh issue develop --base main --name ""
#        env:
#          GH_TOKEN: ${{ github.token }}

      - name: Message
        run: echo "### Test Passed :thumbsup:" >> $GITHUB_STEP_SUMMARY