# Agile Development Workflow
name: AGILE-DEVELOPMENT
run-name: Agile Development

on:

  workflow_call:

jobs: 

  create-slfb:
    name: Create Branch
    runs-on: ubuntu-latest 
    steps:

      - name: Checkout Feature Branch
        uses: actions/checkout@v3

      - name: Issue Develop
        run: |
          slfb=$(echo ${{ github.event.issue.title }} | tr " " "-")
          gh issue develop --base main --name "${{ format('{0}-{1}', github.event.issue.id, $slfb) }}"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Message
        run: echo "### Test Passed :thumbsup:" >> $GITHUB_STEP_SUMMARY