# Agile Development Workflow
name: AGILE-DEVELOPMENT
run-name: Agile Development

on:

  workflow_call:

jobs: 

  slfb:
    name: Setup Dev for SLFB
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:

      - name: Checkout Feature Branch
        uses: actions/checkout@v3

      - name: Set SLFB Name
        id: slfb-name
        run: |
          name=$(echo ${{ github.event.issue.title }} | tr " " "-")
          slfb=$(echo "${{github.event.issue.number}}-${name}" )
          echo "SLFB=$slfb" >> $GITHUB_OUTPUT

      - name: Setup SLFB
        run: gh issue develop ${{github.event.issue.number}} --base main --name "${{ steps.slfb-name.outputs.SLFB }}"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Message SLFB
        run: echo "### SLFB Created :thumbsup:" >> $GITHUB_STEP_SUMMARY

      - name: Setup Codespace
        run: gh codespace create --display-name "${{ steps.slfb-name.outputs.SLFB }}" --repo "${{ github.repository }}" --branch "${{ steps.slfb-name.outputs.SLFB }}" --machine "basicLinux32gb" --retention-period "48h" --default-permissions
        env:
          GH_TOKEN: ${{ secrets.PR_MERGE }}

      - name: Message Codespace
        run: echo "### Codespace Created :thumbsup:" >> $GITHUB_STEP_SUMMARY