# Agile Development Workflow
name: AGILE-DEVELOPMENT
run-name: Agile Development

on:

  workflow_call:

jobs: 

  create-slfb:
    name: Create Branch
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:

      - name: Checkout Feature Branch
        uses: actions/checkout@v3

      - name: Set SLFB Name
        id: slfb-name
        run: |
          name=$(echo ${{ github.event.issue.title }} | tr " " "-")
          slfb=$(echo "${{github.event.issue.number}}-${name}" )
          echo "SLFB=$slfb" >> $GITHUB_OUTPUT

      - name: Issue Develop
        run: gh issue develop ${{github.event.issue.number}} --base main --name "${{ steps.slfb-name.outputs.SLFB }}"
        env:
          GH_TOKEN: ${{ secrets.PAT }}

      - name: Message
        run: echo "### SLFB Created :thumbsup:" >> $GITHUB_STEP_SUMMARY