name: BUILD-LANDING

on:
  workflow_call:
    inputs:
      target-ref:
        required: true
        type: string
      artefact-ref:
        required: true
        type: string        

jobs:
  # Build static site for landing page(s)
  build:
    name: 🔨 Build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Soln Repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ inputs.target-ref }}
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artefact-ref }}
          path: _site
          retention-days: 1

  check-links:
    name: 🔗 Check Links
    needs: [build]
    uses: ./.github/workflows/check-links.yml
    secrets: inherit
    with: 
      artefact-ref: ${{ inputs.artefact-ref }}