name: BUILD-REVEALMD

on:
  workflow_call:
    inputs:
      target-ref:
        required: true
        type: string
      artefact-ref:
        required: true
        type: string
      solution:
          required: true
          type: string 

jobs:

  # Build static sites
  build-static-site:
    name: 🔨 Build Reveal-MD
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Soln Repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ inputs.target-ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      ### All static solutions should use package.json and have lint, test, build as commands
      - name: Install
        run: npm install

      - name: Add version and build date for Reveal-MD
        if: inputs.solution == 'revealmd'
        run: |
          echo -e "${{ inputs.artefact-ref }} \n" >> slides/version.md

      - name: Update build-placeholder
        if: inputs.solution == 'landing'
        run: sed -i 's/BUILD-PLACEHOLDER/${{ inputs.artefact-ref }}/g' src/App.js

      # If linting fails will fail this job
      - name: Run linter 
        run: npm run lint

      # If this tests fail the NPM error will fail this job
      - name: Run tests 
        run: |
          npm run test
          echo "### Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "$(npm run test)" >> $GITHUB_STEP_SUMMARY

      ### NOTE: Reveal.json and Reveal-md.json not passing tests but still working (so run these steps post reveal-md tests)

      - name: Copy reveal.json (configuration) to Reveal-MD
        if: inputs.solution == 'revealmd'
        run: rsync -avh build-files/reveal.json reveal-md

      - name: Copy reveal-md.json (configuration) to Reveal-MD
        if: inputs.solution == 'revealmd'
        run: rsync -avh build-files/reveal-md.json reveal-md

      #- name: Update reveal-md.json
      #  run: | 
      #    jq '.theme = "simple"' reveal-md/reveal-md.json > reveal-md.json
      #    rsync -avh reveal-md.json reveal-md

      - name: 🔨 Run build
        run: npm run build

      - name: Export command needed for Featurevisor
        if: inputs.solution == 'featurevisor'
        run: npm run export

      - name: Copy build output to _site folder (Landing)
        if: inputs.solution == 'landing'
        run: rsync -avh build/ _site

      - name: Copy build output to _site folder (Featurevisor)
        if: inputs.solution == 'featurevisor'
        run: rsync -avh out/ _site

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artefact-ref }}
          ### Output of build should be in _site folder. Maybe make this configurable?
          path: _site
          retention-days: 1