name: CD-PRODUCTION-SCHEDULED
run-name: Scheduled Deployment to Production

on:

  schedule:
    - cron: '55 19 * * 0,1,2,3,4'  
    # Daily run (M-F) of deployments 5:55am Brisbane
    # “At 19:55 on Monday, Tuesday, Wednesday, Thursday, and Sunday.”
    # https://crontab.guru/

  workflow_dispatch:

jobs:

  prd-config:
    name: Get Config for PRD
    outputs:
      rmd: ${{ steps.prd-deploy.outputs.RMD }}    
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:

      - name: Checkout GitOps
        uses: actions/checkout@v3
        with:
          repository: 'dr3dr3/ss-gitops'
          ref: 'main'
          token: ${{ secrets.GHA_PAT }}

      - name: Canary Build Version
        id: can-build
        run: |
          value="$(yq '.deploy.revealmd.build.can' 'config.yml')" || 'ERROR'
          echo "RMD=$value" >> $GITHUB_OUTPUT

      - name: Production Build Version
        id: prd-build
        run: |
          value="$(yq '.deploy.revealmd.build.prd' 'config.yml')" || 'ERROR'
          echo "RMD=$value" >> $GITHUB_OUTPUT

      - name: Decision on PRD deploy
        id: prd-deploy
        run: |
          if [[ ${{ steps.can-build.outputs.RMD }} == ${{ steps.prd-build.outputs.RMD }} ]]; then
            echo "RMD=0" >> $GITHUB_OUTPUT
          else
            echo "RMD=1" >> $GITHUB_OUTPUT
          fi
      
      - name: Decision Output
        run: |
          echo "RMD Deploy Decision: ${{ steps.prd-deploy.outputs.RMD }}"

  # Scheduled dispatch to Production
  scheduled-deploy-production:
    name: Scheduled Deploy to Production
    needs: [prd-config]
    if: ${{ needs.prd-config.outputs.rmd >= 1 }}
    uses: ./.github/workflows/deployment-dispatch.yml
    with:
      target-deploy: 'prd'
    secrets: inherit