name: CD-PRODUCTION-SCHEDULED
run-name: Scheduled Deployment to Production

on:

  schedule:
    - cron: '55 19 * * 0,1,2,3,4'  
    # Daily run (M-F) of deployments 5:55am Brisbane
    # “At 19:55 on Monday, Tuesday, Wednesday, Thursday, and Sunday.”
    # https://crontab.guru/

  workflow_dispatch:

jobs:

  config-prd:
    name: Get Config for PRD
    outputs:
      blue: ${{ steps.build-blue.outputs.BLUE }}    
      green: ${{ steps.build-green.outputs.GREEN }}   
      decision: ${{ steps.deploy-decision.outputs.DECISION }} 
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:

      - name: Checkout GitOps
        uses: actions/checkout@v3
        with:
          repository: 'dr3dr3/ss-gitops'
          ref: 'main'
          token: ${{ secrets.GHA_PAT }}

      - name: Build for Production (Blue)
        id: build-blue
        run: |
          revealmd="$(yq '.deploy.prd.blue.revealmd' 'builds.yml')" || 'ERROR'
          landing="$(yq '.deploy.prd.blue.landing' 'builds.yml')" || 'ERROR'
          value="${revealmd}.${landing}"
          echo $value
          echo "BLUE=$value" >> $GITHUB_OUTPUT

      - name: Build for Production (Green)
        id: build-green
        run: |
          revealmd="$(yq '.deploy.prd.green.revealmd' 'builds.yml')" || 'ERROR'
          landing="$(yq '.deploy.prd.green.landing' 'builds.yml')" || 'ERROR'
          value="${revealmd}.${landing}"
          echo $value
          echo "GREEN=$value" >> $GITHUB_OUTPUT

      - name: Decision if deploy to PRD GREEN
        id: deploy-decision
        run: |
          if [[ ${{ steps.build-blue.outputs.BLUE }} == ${{ steps.build-green.outputs.GREEN }} ]]; then
            echo "DECISION=NO" >> $GITHUB_OUTPUT
          else
            echo "DECISION=YES" >> $GITHUB_OUTPUT
          fi
      
      - name: Decision Decision
        run: |
          echo "Reveal-MD Deploy Decision: ${{ steps.deploy-decision.outputs.DECISION }}"

  config-deploy:
    name: Get deployment config
    needs: [config-prd]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    outputs:
      stage-repo: ${{ steps.setoutput.outputs.REF }}
      site-url: ${{ steps.setoutput.outputs.URL }}
    steps:

    - name: Checkout GitOps
      uses: actions/checkout@v3
      with:
        repository: 'dr3dr3/ss-gitops'
        ref: 'main'
        token: ${{ secrets.GHA_PAT }}

    - name: Output Config
      id: setoutput
      run: |
        ref="$(yq '.repositories.deployment.prd.ref' 'repositories.yml')" || 'ERROR'
        echo "REF=$ref" >> $GITHUB_OUTPUT
        url="$(yq '.repositories.deployment.prd.site-url' 'repositories.yml')" || 'ERROR'
        echo "URL=$url" >> $GITHUB_OUTPUT

  # Scheduled dispatch to Production
  scheduled-deploy-production:
    name: Scheduled Deploy to Production
    needs: [config-prd,config-deploy]
    if: needs.config-prd.outputs.decision == 'YES'
    uses: ./.github/workflows/deployment-dispatch.yml
    with:
      blue-green: 'green'
      site-url: ${{ needs.config-deploy.outputs.site-url }}
      target-repo: ${{ needs.config-deploy.outputs.stage-repo }}
    secrets: inherit