# Continuous Delivery Scheduled Deployments
name: CONTINUOUS-DEPLOYMENT-SCHEDULER
run-name: Scheduled Deployments

on:
  schedule:
    - cron: '55 19 * * 1'          # Weekly run for Production deployments

jobs:

  # Scheduled dispatch to Production
  scheduled-deploy-production:
    name: Scheduled Deploy to Production
    if: github.event.schedule == '55 19 * * 1'
    uses: ./.github/workflows/continuous-deployment.yml
    with: 
      target-ref: 'main'
      deploy-target: 'prd'
    secrets: inherit

  # Dispatch to Deploy to Production Environment
  dispatch-prd:
    name: Dispatch Production Deployment
    needs: [continuous-delivery]
    uses: dr3dr3/ss-pipeline/.github/workflows/continuous-deployment.yml@main
    with:
      from-soln: 'na'
      target-ref: 'main'
      target-deploy: 'prd'
    secrets: inherit