# NOTE: Must use this in same workflow as artefact upload
name: CHECK-LINKS

on:
  workflow_call:
    inputs:
      artefact-ref:
        required: true
        type: string

jobs:

  check-links:
    name: Checking Links 🔗
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artefact-ref }}
          path: _site

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Linkinator
        run: npm install linkinator

      - name: Check links to JS files
        id: results-js
        run: |
          echo $(npx linkinator "_site/**/*.js" --verbosity error)
          echo $(npx linkinator "_site/**/*.js" --format JSON) >> links-js.json
          echo 'JS='$(jq '.passed' links-js.json) >> $GITHUB_OUTPUT

      - name: Fail workflow - JS
        if: ${{ steps.results-js.outputs.JS != 'true' }}
        run: exit 1

      - name: Check links to HTML files
        id: results-html
        run: |
          echo $(npx linkinator "_site/**/*.html" --verbosity error)
          echo $(npx linkinator "_site/**/*.html" --format JSON) >> links-html.json
          echo 'HTML='$(jq '.passed' links-html.json) >> $GITHUB_OUTPUT

      - name: Fail workflow - HTML
        if: ${{ steps.results-html.outputs.HTML != 'true' }}
        run: exit 1

      - name: Check links to CSS files
        id: results-css
        run: |
          echo $(npx linkinator "_site/**/*.css" --verbosity error)
          echo $(npx linkinator "_site/**/*.css" --format JSON) >> links-css.json
          echo 'CSS='$(jq '.passed' links-css.json) >> $GITHUB_OUTPUT

      - name: Fail workflow - CSS
        if: ${{ steps.results-css.outputs.CSS != 'true' }}
        run: exit 1

#      - name: Check links to MD files
#        id: results-md
#        run: |
#          echo $(npx linkinator "_site/**/*.md")
#          echo $(npx linkinator "_site/**/*.md" --format JSON --markdown) >> links-md.json
#          echo 'MD='$(jq '.passed' links-md.json) >> $GITHUB_OUTPUT

#      - name: Fail workflow - MD
#        if: ${{ steps.results-md.outputs.MD != 'true' }}
#        run: exit 1

#      - name: Check external links
#        id: results-ext
#        run: |
#          echo npx linkinator "https://dr3dr3.github.io/devops-demo-stg" --recurse
#          echo $(npx linkinator "npx linkinator "https://dr3dr3.github.io/devops-demo-stg" --recurse --format JSON) >> links-ext.json
#          echo 'EXT='$(jq '.passed' links-ext.json) >> $GITHUB_OUTPUT

#      - name: Fail workflow - External
#        if: ${{ steps.results-ext.outputs.EXT != 'true' }}
#        run: exit 1