# NOTE: Must use this in same workflow as artefact upload
name: CHECK-LINKS

on:
  workflow_call:
    inputs:
      artefact-ref:
        required: true
        type: string
      toggle:
        required: true
        type: boolean

jobs:

  check-links:
    name: Checking Links 🔗
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:

      - name: Checkout SS-Pipelines
        uses: actions/checkout@v3
        with:
          repository: 'dr3dr3/ss-pipeline'
          ref: 'main'
          token: ${{ secrets.GHA_PAT }}

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artefact-ref }}
          path: _site

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # https://github.com/JustinBeckwith/linkinator
      - name: Install Linkinator
        run: |
          npm install linkinator

      - name: Check links 
        id: check-links
        if: inputs.toggle == true
        run: |
          echo "### Linkinator" >> $GITHUB_STEP_SUMMARY
          cd _site
          ls
          npx linkinator "**/*" --config "../config/linkinator.config.json"
          echo $(npx linkinator "**/*" --config "../config/linkinator.config.json") >> $GITHUB_STEP_SUMMARY
          echo "Done: GitHub Step Summary"
          echo $(npx linkinator "**/*" --config "../config/linkinator.config.json") >> links-html.json
          echo "Done: Create links-html.json"
          echo 'RESULT='$(jq '.passed' links-html.json) >> $GITHUB_OUTPUT
          echo "Done: Set HTML variable"

      - name: Fail workflow
        if: steps.check-links.outputs.RESULT != 'true' && inputs.toggle == true
        run: exit 1
