name: CHECKS-SCHEDULED
run-name: Scheduled Checks

on:

  schedule:
    - cron: '55 20 * * 0'  # Sun at 6:55am Brisbane
    # https://crontab.guru/

  workflow_dispatch:

jobs:

  # Performance testing using Google Lighthouse
  # https://github.com/marketplace/actions/lighthouse-ci-action
  lighthouse:
    name: Google Lighthouse Report
    if: github.event.schedule == '55 20 * * 0' || github.event_name == 'workflow_dispatch'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'dr3dr3/ss-pipeline'
          ref: 'main'
          token: ${{ secrets.GHA_PAT }}

      - name: Run Lighthouse on urls and validate with lighthouserc
        id: lighthouse-ci
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://www.andredreyer.com
            https://www.andredreyer.com/slides/version.html
          configPath: "./config/lighthouserc.json"
          runs: 3
          uploadArtifacts: true

      - name: Results
        run: |
          echo "### Lighthouse Results :thumbsup:" >> $GITHUB_STEP_SUMMARY
          echo "URL1 Performance: ${{ fromJSON(steps.lighthouse-ci.outputs.manifest)[0].summary.performance }}" >> $GITHUB_STEP_SUMMARY

  # Test for public javascript library vulnerabilities
  security:
    name: Is Website Vulnerable?
    if: github.event.schedule == '55 20 * * 0' || github.event_name == 'workflow_dispatch'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Test for public javascript library vulnerabilities 
        uses: lirantal/is-website-vulnerable@main
        with:
          scan-url: "https://www.andredreyer.com/slides/version.html"

### Results of checks send to workflow outputs

### If any checks fail then add issue to pause Prod deployments and alert via IFTTT