# Deploy static site to GitHub Pages
name: DEPLOY-GITHUB-PAGES

on:
  workflow_call:
    inputs:
      artefact-ref:
        required: true
        type: string
      deploy-to:
        required: true
        type: string 

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:

  echo:
    name: Picking SS Host
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:

      - name: Echo
        run: echo "Starting deploy to ${{ inputs.deploy-to }}"

  deploy-ghp:
    name: 🚀 Deploy GHP
    if: inputs.deploy-to == 'GHP'
    environment:
      # Ignore lint error regarding name value below. It should be github-pages
      name: 'github-pages'
      url: ${{ steps.deployment.outputs.page_url }}
    outputs:
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artefact-ref }}
          path: _site

      - name: Upload Pages artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site/
          
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v1

      - name: Summary
        run: |
          echo "### Deploy complete! :green_apple:" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.deployment.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY