# Update config held in GitOps Repository
name: GITOPS-UPDATE

on:
  workflow_call:
    inputs:
      config-item:
        required: true
        type: string
      config-value:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      config-item:
        description: Configuration Item
        required: true
        type: string
      config-value:
        description: Configuration Value
        required: true
        type: string

jobs:
  update-config:
    name: Update GitOps Config
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:

      - name: Checkout GitOps
        uses: actions/checkout@v3
        with:
          repository: 'dr3dr3/ss-gitops'
          ref: 'main'
          token: ${{ secrets.GHA_PAT }}

      - name: Update config yaml
        run: yq -i '.${{ inputs.config-item }} = "${{ inputs.config-value }}"' config.yml

      - name: Test
        id: test
        run: |
          value="$(yq '.${{ inputs.config-item }}' 'config.yml')" || 'ERROR'
          echo "Build from config: $value"