name: CREATE-NEW-CODESPACE

on:

  workflow_call:

jobs: 

  codespace:
    name: Setup Codespace for SLFB
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:

      - name: Checkout Main Branch
        uses: actions/checkout@v3

      - name: Set SLFB Name
        id: slfb-name
        run: |
          name=$(echo ${{ github.event.issue.title }} | tr " " "-")
          slfb=$(echo "${{github.event.issue.number}}-${name}" )
          echo "${slfb}"
          echo "SLFB=$slfb" >> $GITHUB_OUTPUT

      - name: Setup Codespace
        run: gh codespace create --display-name "${{ steps.slfb-name.outputs.SLFB }}" --repo "${{ github.repository }}" --branch "${{ steps.slfb-name.outputs.SLFB }}" --machine "basicLinux32gb" --retention-period "48h" --default-permissions
        env:
          GH_TOKEN: ${{ secrets.CREATE_CODESPACES }}

      - name: Message Codespace
        run: echo "### Codespace Created :thumbsup:" >> $GITHUB_STEP_SUMMARY
  