# Send relevant notifications to IFTTT webhook
name: IFTTT
run-name: IFTTT Notification

on:
  workflow_call:
    inputs:
      phase:
        required: true
        type: string
      outcome:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      phase:
        description: Configuration Item
        required: true
        default: 'test'
        type: choice
        options:
        - test
        - build
        - ci
        - stg
        - can
        - prd
      outcome:
        description: Configuration Value
        required: true
        default: 'default'
        type: choice
        options:
        - default
        - fail
        - success

jobs:
    ifttt-webhook-call:
        name: IFTTT Webhook Calls
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
    
        - name: Build Fail
          if: inputs.phase == 'build' && inputs.outcome == 'fail' || inputs.phase == 'test'
          run: |
            curl -X POST -H 'Content-Type: application/json' -d '{"phase":"build", "outcome":"fail"}' https://maker.ifttt.com/trigger/gha_build_red/json/with/key/${{ secrets.IFTTT }}
            sleep 5

        - name: Build Success
          if: inputs.phase == 'build' && inputs.outcome == 'success' || inputs.phase == 'test'
          run: |
            curl -X POST -H 'Content-Type: application/json' -d '{"phase":"build", "outcome":"success"}' https://maker.ifttt.com/trigger/gha_build_green/json/with/key/${{ secrets.IFTTT }}
            sleep 5
  
        - name: CI Fail
          if: inputs.phase == 'ci' && inputs.outcome == 'fail' || inputs.phase == 'test'
          run: |
            curl -X POST -H 'Content-Type: application/json' -d '{"phase":"ci", "outcome":"fail"}' https://maker.ifttt.com/trigger/gha_ci_red/json/with/key/${{ secrets.IFTTT }}
            sleep 5
  
        - name: CI Success
          if: inputs.phase == 'ci' && inputs.outcome == 'success' || inputs.phase == 'test'
          run: |
            curl -X POST -H 'Content-Type: application/json' -d '{"phase":"ci", "outcome":"success"}' https://maker.ifttt.com/trigger/gha_ci_red/json/with/key/${{ secrets.IFTTT }}
            sleep 5
    
        - name: STG Fail
          if: inputs.phase == 'stg' && inputs.outcome == 'fail' || inputs.phase == 'test'
          run: |
            curl -X POST -H 'Content-Type: application/json' -d '{"phase":"stg", "outcome":"fail"}' https://maker.ifttt.com/trigger/gha_stg_red/json/with/key/${{ secrets.IFTTT }}
            sleep 5
    
        - name: STG Success
          if: inputs.phase == 'stg' && inputs.outcome == 'success' || inputs.phase == 'test'
          run: |
            curl -X POST -H 'Content-Type: application/json' -d '{"phase":"stg", "outcome":"success"}' https://maker.ifttt.com/trigger/gha_stg_green/json/with/key/${{ secrets.IFTTT }}
            sleep 5
      
        - name: CAN Fail
          if: inputs.phase == 'can' && inputs.outcome == 'fail' || inputs.phase == 'test'
          run: |
            curl -X POST -H 'Content-Type: application/json' -d '{"phase":"can", "outcome":"fail"}' https://maker.ifttt.com/trigger/gha_can_red/json/with/key/${{ secrets.IFTTT }}
            sleep 5
      
        - name: CAN Success
          if: inputs.phase == 'can' && inputs.outcome == 'success' || inputs.phase == 'test'
          run: |
            curl -X POST -H 'Content-Type: application/json' -d '{"phase":"can", "outcome":"success"}' https://maker.ifttt.com/trigger/gha_can_green/json/with/key/${{ secrets.IFTTT }}
            sleep 5

        - name: PRD Fail
          if: inputs.phase == 'prd' && inputs.outcome == 'fail' || inputs.phase == 'test'
          run: |
            curl -X POST -H 'Content-Type: application/json' -d '{"phase":"prd", "outcome":"fail"}' https://maker.ifttt.com/trigger/gha_prd_red/json/with/key/${{ secrets.IFTTT }}
            sleep 5
        
        - name: PRD Success
          if: inputs.phase == 'prd' && inputs.outcome == 'success' || inputs.phase == 'test'
          run: |
            curl -X POST -H 'Content-Type: application/json' -d '{"phase":"prd", "outcome":"success"}' https://maker.ifttt.com/trigger/gha_prd_green/json/with/key/${{ secrets.IFTTT }}
            sleep 5
  