name: REPOSITORY-VARIABLES
run-name: Set / validate configured variables in GitHub repositories

on:
  workflow_call:
    inputs:
      repo-gitops:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      repo-gitops:
        description: GitOps Repository
        required: true
        type: string

jobs:
  repo-variables:
    name: Setup / Validate Repository Variables
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.REPO_VARS }}

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo-gitops }}
          ref: 'main'
          token: ${{ secrets.GHA_PAT }}

      - name: Get Reveal-MD Repo
        id: revealmd-repo
        run: echo "CONFIG=$(yq '.repositories.solutions.revealmd.ref' 'repositories.yml')" >> $GITHUB_OUTPUT

      - name: Get Variable REVEALMD.CI_PATTERN
        id: revealmd-cipattern
        run: echo "CONFIG=$(yq '.repositories.solutions.revealmd.var-CI_PATTERN' 'repositories.yml')" >> $GITHUB_OUTPUT

      ##### Checkout each repo so GH CLI can setup variables for the repository

      ##### Repo = GitOPS

      - name: Checkout Reveal-MD
        uses: actions/checkout@v3
        with:
          repository: ${{ steps.revealmd-repo.outputs.CONFIG }}
          ref: 'main'
          token: ${{ secrets.GHA_PAT }}

      - name: Set Variable - REVEALMD.CI_PATTERN
        run: gh variable set CI_PATTERN --body "${{ steps.revealmd-cipattern.outputs.CONFIG }}"
