# Add release and tag in GitHub for commits on Main
name: TAG-RELEASE

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      target-ref:
        required: true
        type: string
      feature:
        required: true
        type: string

jobs:
  tag-release:
    name: Tag Release
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Soln Repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ inputs.target-ref }}
          token: ${{ secrets.GHA_PAT }}

      - name: Download Build Artefacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.tag }}
          path: _site

      - name: Bundle Artefacts
        run: tar czf build.tar.gz _site
      
      - name: GitHub Release
        run: gh release create "${{ inputs.tag }}" "./build.tar.gz#Build-Artefact" --target ${{ inputs.target-ref }} --title ${{ inputs.feature }} --notes "Get from issue"
        env:
          GH_TOKEN: ${{ secrets.GHA_PAT }}

### ADD: Upload build artefacts to release (will use in deploys). First need to download build artefacts.
### ADD: Get release notes from related issue (if issue ID in commit message) and put into body of release