# Add release and tag in GitHub for commits on Main
name: TAG-RELEASE

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      target-ref:
        required: true
        type: string
      feature:
        required: true
        type: string

jobs:
  tag-release:
    name: Release
    if: ${{ github.event_name != 'workflow_dispatch' }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Soln Repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ inputs.target-ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Build Artefacts
        # Need to use this in same workflow as create artefacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.tag }}
          path: _site

      - name: Bundle Artefacts
        run: tar -cvzf build.tar.gz _site
      
      - name: GitHub Release
        run: gh release create "${{ inputs.tag }}" "./build.tar.gz#Build-Artefact" --target "${{ inputs.target-ref }}" --title "${{ inputs.tag }}" --notes "${{ inputs.feature }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

### ADD: Get release notes from related issue (if issue ID in commit message) and put into body of release